openapi: 3.1.0
info:
  title: OpenSearch Index Transforms API
  description: OpenSearch Index Transforms API
  version: 1.0.0
paths:
  /_plugins/_transform:
    get:
      operationId: transform.search.0
      x-operation-group: transform.search
      x-version-added: '1.0'
      description: Returns the details of all transform jobs.
      externalDocs:
        url: https://opensearch.org/docs/latest/im-plugin/index-transforms/transforms-apis/#get-a-transform-jobs-details
      parameters:
        - $ref: '#/components/parameters/transform.search::query.from'
        - $ref: '#/components/parameters/transform.search::query.search'
        - $ref: '#/components/parameters/transform.search::query.size'
        - $ref: '#/components/parameters/transform.search::query.sortDirection'
        - $ref: '#/components/parameters/transform.search::query.sortField'
      responses:
        '200':
          $ref: '#/components/responses/transform.search@200'
  /_plugins/_transform/{id}:
    get:
      operationId: transform.get.0
      x-operation-group: transform.get
      x-version-added: '1.0'
      description: Returns the status and metadata of a transform job.
      externalDocs:
        url: https://opensearch.org/docs/latest/im-plugin/index-transforms/transforms-apis/#get-a-transform-jobs-details
      parameters:
        - $ref: '#/components/parameters/transform.get::path.id'
      responses:
        '200':
          $ref: '#/components/responses/transform.get@200'
    put:
      operationId: transform.put.0
      x-operation-group: transform.put
      x-version-added: '1.0'
      description: Create an index transform, or update a transform if if_seq_no and if_primary_term are provided.
      externalDocs:
        url: https://opensearch.org/docs/latest/im-plugin/index-transforms/transforms-apis/#create-a-transform-job      
      parameters:
        - $ref: '#/components/parameters/transform.put::path.id'
        - $ref: '#/components/parameters/transform.put::query.if_primary_term'
        - $ref: '#/components/parameters/transform.put::query.if_seq_no'
      requestBody:
        $ref: '#/components/requestBodies/transform.put'
      responses:
        '200':
          $ref: '#/components/responses/transform.put@200'
    delete:
      operationId: transform.delete.0
      x-operation-group: transform.delete
      x-version-added: '1.0'
      description: Delete an index transform.
      externalDocs:
        url: https://opensearch.org/docs/latest/im-plugin/index-transforms/transforms-apis/#delete-a-transform-job
      parameters:
        - $ref: '#/components/parameters/transform.delete::path.id'
      responses:
        '200':
          $ref: '#/components/responses/transform.delete@200'
  /_plugins/_transform/{id}/_start:
    post:
      operationId: transform.start.0
      x-operation-group: transform.start
      x-version-added: '1.0'
      description: Start transform.
      externalDocs:
        url: https://opensearch.org/docs/latest/im-plugin/index-transforms/transforms-apis/#start-a-transform-job
      parameters:
        - $ref: '#/components/parameters/transform.start::path.id'
      responses:
        '200':
          $ref: '#/components/responses/transform.start@200'
  /_plugins/_transform/{id}/_stop:
    post:
      operationId: transform.stop.0
      x-operation-group: transform.stop
      x-version-added: '1.0'
      description: stop transform.
      externalDocs:
        url: https://opensearch.org/docs/latest/im-plugin/index-transforms/transforms-apis/#stop-a-transform-job
      parameters:
        - $ref: '#/components/parameters/transform.stop::path.id'
      responses:
        '200':
          $ref: '#/components/responses/transform.stop@200'
  /_plugins/_transform/{id}/_explain:
    get:
      operationId: transform.explain.0
      x-operation-group: transform.explain
      x-version-added: '1.0'
      description: Returns the status and metadata of a transform job.      
      externalDocs:
        url: https://opensearch.org/docs/latest/im-plugin/index-transforms/transforms-apis/#get-the-status-of-a-transform-job
      parameters:
        - $ref: '#/components/parameters/transform.explain::path.id'
      responses:
        '200':
          $ref: '#/components/responses/transform.explain@200'
  /_plugins/_transform/_preview:
    get:
      operationId: transform.preview.0
      x-operation-group: transform.preview
      x-version-added: '1.0'
      description: Returns a preview of what a transformed index would look like.
      externalDocs:
        url: https://opensearch.org/docs/latest/im-plugin/index-transforms/transforms-apis/#preview-a-transform-jobs-results
      responses:
        '200':
          $ref: '#/components/responses/transform.preview@200'
components:
  requestBodies:
    transform.put:
      content:
        application/json:
          schema:
            $ref: '../schemas/transform._common.yaml#/components/schemas/Transform'
  responses:
    transform.search@200:
      content:
        application/json:
          schema:
            $ref: '../schemas/transform._common.yaml#/components/schemas/TransformsResponse'
    transform.get@200:
      content:
        application/json:
          schema:
            $ref: '../schemas/transform._common.yaml#/components/schemas/TransformEntity'
    transform.put@200:
      content:
        application/json:
          schema:
            $ref: '../schemas/transform._common.yaml#/components/schemas/TransformEntity'
    transform.delete@200:
      description: ''
    transform.start@200:
      content:
        application/json:
          schema:
            $ref: '../schemas/_common.yaml#/components/schemas/AcknowledgedResponseBase'
    transform.stop@200:
      content:
        application/json:
          schema:
            $ref: '../schemas/_common.yaml#/components/schemas/AcknowledgedResponseBase'
    transform.explain@200:
      content:
        application/json:
          schema:
            $ref: '../schemas/transform._common.yaml#/components/schemas/ExplainResponse'
    transform.preview@200:
      content:
        application/json:
          schema:
            $ref: '../schemas/transform._common.yaml#/components/schemas/Preview'
  parameters:
    transform.get::path.id:
      name: id
      in: path
      description: Transform to access
      required: true
      schema:
        $ref: '../schemas/_common.yaml#/components/schemas/Id'
      style: simple
    transform.put::path.id:
      name: id
      in: path
      description: Transform to create/update
      required: true
      schema:
        $ref: '../schemas/_common.yaml#/components/schemas/Id'
      style: simple
    transform.delete::path.id:
      name: id
      in: path
      description: Transform to delete
      required: true
      schema:
        $ref: '../schemas/_common.yaml#/components/schemas/Id'
      style: simple
    transform.start::path.id:
      name: id
      in: path
      description: Transform to start
      required: true
      schema:
        $ref: '../schemas/_common.yaml#/components/schemas/Id'
      style: simple
    transform.stop::path.id:
      name: id
      in: path
      description: Transform to stop
      required: true
      schema:
        $ref: '../schemas/_common.yaml#/components/schemas/Id'
      style: simple
    transform.explain::path.id:
      name: id
      in: path
      description: Transform to explain
      required: true
      schema:
        $ref: '../schemas/_common.yaml#/components/schemas/Id'
      style: simple
    transform.put::query.if_seq_no:
      name: if_seq_no
      in: query
      description: Only perform the operation if the document has this sequence number.
      required: false
      schema:
        $ref: '../schemas/_common.yaml#/components/schemas/SequenceNumber'
      style: form
    transform.put::query.if_primary_term:
      name: if_primary_term
      in: query
      description: Only perform the operation if the document has this primary term.
      required: false
      schema:
        type: number
      style: form
    transform.search::query.size:
      name: size
      in: query
      description: Specifies the number of transforms to return. Default is `10`.
      required: false
      schema:
        type: number
      style: form
    transform.search::query.from:
      name: from
      in: query
      description: The starting transform to return. Default is `0`.
      required: false
      schema:
        type: number
      style: form
    transform.search::query.search:
      name: search
      in: query
      description: The search term to use to filter results.
      required: false
      schema:
        type: string
      style: form
    transform.search::query.sortField:
      name: sortField
      in: query
      description: The field to sort results with.
      required: false
      schema:
        type: string
      style: form
    transform.search::query.sortDirection:
      name: sortDirection
      in: query
      description: Specifies the direction to sort results in. Can be `ASC` or `DESC`. Default is `ASC`.
      required: false
      schema:
        type: string
      style: form
