openapi: 3.1.0
info:
  title: OpenSearch _core API
  description: OpenSearch _core API
  version: 1.0.0
paths:
  /:
    get:
      operationId: info.0
      x-operation-group: info
      x-version-added: '1.0'
      description: Returns basic information about the cluster.
      externalDocs:
        url: https://opensearch.org/docs/latest
      parameters: []
      responses:
        '200':
          $ref: '#/components/responses/info@200'
components:
  requestBodies:
    index:
      content:
        application/json:
          schema:
            type: object
            description: The document
      required: true
  responses:
    info@200:
      description: ''
      content:
        application/json:
          schema:
            type: object
            properties:
              cluster_name:
                $ref: '../schemas/_common.yaml#/components/schemas/Name'
              cluster_uuid:
                $ref: '../schemas/_common.yaml#/components/schemas/Uuid'
              name:
                $ref: '../schemas/_common.yaml#/components/schemas/Name'
              tagline:
                type: string
              version:
                $ref: '../schemas/_common.yaml#/components/schemas/OpensearchVersionInfo'
            required:
              - cluster_name
              - cluster_uuid
              - name
              - tagline
              - version
