name: Draft a Release

on:
  push:
    tags:
      - "*"

jobs:
  draft-a-release:
    name: Draft a Release
    runs-on: ubuntu-latest
    permissions:
      contents: write
      issues: write

    steps:
      - name: Checkout the repo
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "20"

      - name: Build
        run: npm ci && npm run merge

      - name: Upload Artifacts
        id: upload
        uses: actions/upload-artifact@v4
        with:
          name: build
          path: |
            build/*

      - name: Release Specification to GitHub
        id: release
        uses: marvinpinto/action-automatic-releases@v1.2.1
        with:
          repo_token: ${{ secrets.GITHUB_TOKEN }}
          automatic_release_tag: ${{ github.ref_name }}
          prerelease: true
          title: OpenSearch OpenAPI Spec (${{ github.ref_name }})
          files: |
            LICENSE.txt
            build/*

      - name: Extract Changelog
        id: changelog
        uses: sean0x42/markdown-extract@v2
        with:
          file: CHANGELOG.md
          pattern: Unreleased

      - name: Update Release Description
        id: update
        uses: tubone24/update_release@v1.3.1
        env:
          TAG_NAME: ${{ github.ref_name }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          body: |
            ${{ steps.changelog.outputs.markdown }}

            ### Links
            - [Build Artifact](${{ steps.upload.outputs.artifact-url }})
